### ISSUE TITLE
Logging error?

### ISSUE THREAD

**Issue by AngelJumbo** [area-of-dev/apprepo.AppImage#2]
I use void linux and when I use this program to install something I get this:

`--- Logging error ---
Traceback (most recent call last):
  File "/tmp/.mount_apprepZXdaBB/lib64/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_apprepZXdaBB/lib64/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_apprepZXdaBB/lib64/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/tmp/.mount_apprepZXdaBB/lib64/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/tmp/.mount_apprepZXdaBB/apprepo/console.py", line 70, in <module>
    sys.exit(application.run(options, args))
  File "/tmp/.mount_apprepZXdaBB/vendor/hexdi/decorator.py", line 69, in inject_func_args
    return func(*resolves)
  File "/tmp/.mount_apprepZXdaBB/apprepo/modules/cmd/application.py", line 29, in run
    logger.info('Console mode, config: {}'.format(options.config))
Message: 'Console mode, config: /home/anarv/.config/apprepo/default.conf'
`

**Comment by AlexWoroschilow** [comment]
Hi, thank you for the bugreport,
according to the trace it looks like there are some problems with the
sockets...
for some reason the python can not open sockets...

You can try to set log level  as CRITICAL to disable all the rest...
apprepo --loglevel=CRITICAL

That is best i can advice with the given information :)

Have a nice day,
Alex





Am Sa., 26. März 2022 um 04:07 Uhr schrieb AngelJumbo <
***@***.***>:
